update spring #141
feelpp/toolbox pull request #142
Opened 2022-10-13 08:52 UTC by jobinhio

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/toolbox/pulls) for the same change?
- [x] Have you fixed a Bug ?
- [ ] Have you added the documentation of the example or benchmark ?
- [x] Have you successfully run the example or benchmark?
- [ ] Have you documented the results?
- [ ] Have you added the images to the documentation?
- [ ] Have you added the vtkjs files for 3D visualization in the documentation?
- [ ] Have you added the vtkjs files to a Data Management Plateform _e.g_ https://girder.math.unistra.fr

-----

2022-10-13 09:30 UTC, prudhomm requested changes
- the report of the simulation is missing  as well as the note regarding the report in the documentation see #136 
- add imagesprefix support as described in #144
- add authors to metadata #145

2022-10-13 09:30 UTC, prudhomm commented on examples/modules/csm/examples/spring/spring.json
> +      "author": [""],
add authors see #145

2022-11-04 10:39 UTC, jobinhio commented
here are the results of displacement solid.
![spring_displacement](https://user-images.githubusercontent.com/90212689/195541895-83825584-4bb2-43d9-80ae-d8001bda079e.png)

here are the results of von mises criterion.
![spring_von_mises_criterion](https://user-images.githubusercontent.com/90212689/195542345-7368192c-2fd0-4e35-bacb-ef7bb7ecf933.png)

2022-11-07 19:32 UTC, prudhomm approved these changes

2022-11-07 19:32 UTC, prudhomm commented on examples/modules/csm/pages/spring/README.adoc
> +NOTE: The report of the execution of the command above is available xref:spring/solid-informations.adoc[here].
informations -> information (rename the adoc file)

2022-11-07 19:33 UTC, merged